### PR TITLE
feat(main): add argument --no-banner

### PR DESCRIPTION
**Pull request by 0xlildoudou**
#### Which category is this pull request?

- [x] A new feature/enhancement.
- [ ] Fix an issue/feature-request.
- [ ] An improvement to existing modules.
- [ ] Other (Please mention below).

#### Where has this been tested?

- Python Version
    - [x] v3.x
    - [ ] v2.x
- Operating System:
    - [ x] Linux (debian 12)
    - [ ] Windows
    - [ ] MacOS

#### Does this close any currently open issues? 
no

#### Does this add any new dependency?
no

#### Does this add any new command line switch/argument?
add new argument `--no-banner` for remove banner (default false)

### CODE REVIEW

**Comment by 0xInfection** [comment]
hi @0xlildoudou, thanks for the PR! can you help me understand under what use case(s) this will be helpful to users? :D

**Comment by 0xlildoudou** [comment]
Hi @0xInfection ,

for my part, this is one of the improvements I've added to the tools. I launch the tool in a Kubernetes cluster and I rely on the stdout output to know if everything goes well during the launch. The banner is therefore a bit problematic.
In addition, many automated tools need to retrieve the stdout, so the banner is problematic.
By default, the banner remains displayed. It's only a minor addition to the tool.

**Comment by 0xInfection** [comment]
I see. For the integrations was the output to file flag not working for you enough? What improvements can you suggest that would make the output to file feature more useful?

**Comment by 0xlildoudou** [comment]
I use the output file with the "--no-banner" as a same time in my fork.
stdout --> wafw00f status
output file --> wafw00f status.

I have work for add wafw00f status log for container integration but actually it's dirty 😅

**Comment by 0xlildoudou** [comment]
@0xInfection what's next for this PR ?

**Comment by 0xInfection** [comment]
hi @0xlildoudou! I'm just confused around the use-case yet, and I am looking for suggestions where the output to file (json/csv) is not working well for your usecase. Maybe you can help suggest how we can improve your integration?

**Comment by 0xInfection** [comment]
closing this due to inactivity, feel free to reopen with additional utility/features.

**Comment by laluka** [comment]
You're retarded 👏🎂🤝
Regards,

**Comment by 0xlildoudou** [comment]
top 👍

**Pull request closed without merging**
