### PR TITLE
+1 cookie based signature for Fortiweb

### PR DESCRIPTION
**Pull request by s0md3v**

### CODE REVIEW

**Comment by s0md3v** [comment]
> Not all sites running Fortiweb directly set cookies.

That's why we have multiple signatures for each WAF. We never know which one will match the configuration being used by the target website.

Also, calling it not unique would be fine only and only if it has been seen in the wild at least one time without any implementation of the said WAF.

**Comment by 0xInfection** [comment]
> That's why we have multiple signatures for each WAF. We never know which one will match the configuration being used by the target website.

We are speaking of Fortiweb in specific. 

I can give you examples of 3 sites running Fortiweb, and none of them setting cookies upon first request instant. Fortiweb can really not be detected without attack simulation, why go for ones which can give false positives when you have unique reliable ones at hand. :)

**Comment by s0md3v** [comment]
Read my comment again, slowly this time, especially the last line.

**Comment by 0xInfection** [comment]
[Have a look here](https://cookiepedia.co.uk/cookies/cookiesession1) about the sites setting a first party cookie as `cookiesession1`. Taking up the first URl from the site which is `www.amd.com`, you can clearly see it is setting a `cookiesession1` cookie while it is actually running behind Kona Site Defender from Akamai. I will say no more. :)

**Comment by 0xInfection** [comment]
[Have a look here](https://cookiepedia.co.uk/website/www.amd.com) about a site setting a first party cookie as `cookiesession1`. You can clearly see the cookie being set while it is actually running behind Kona Site Defender from Akamai. 

I will say no more, rest assured you're competent enough to understand. :)

**Comment by sandrogauci** [comment]
thanks for the contribution @s0md3v .. will close this for now as we'll need a more unique way of identifying such a WAF without causing too many false positives. @0xInfection has been doing a bunch of updates to avoid such false positives. If you do find a new way to identify the Fortiweb WAF, you're more than welcome to update your pull.

**Pull request closed without merging**
