### PR TITLE
Add support to ppc64le

### PR DESCRIPTION
**Pull request by gururajrkatti**
#### Which category is this pull request?

- [ ] A new feature/enhancement.
- [ ] Fix an issue/feature-request.
- [ ] An improvement to existing modules.
- [x] Other (Please mention below).
Adding support to new platform ppc64le

#### Where has this been tested?

- Python Version
    - [x] v3.x
    - [ ] v2.x
- Operating System:
    - [x] Linux (Please specify distro)
    - [ ] Windows
    - [ ] MacOS
ubuntu xenial
#### Does this close any currently open issues? No
[Mention any issue which this PR closes]

#### Does this add any new dependency?
[Mention if this PR includes any new library]

#### Does this add any new command line switch/argument?
[Mention if the changes add any new arguments like `--arg`]

#### Any other comments you would like to make?
[Anything more you'd want the reviewer to know]

### CODE REVIEW

**Comment by 0xInfection** [comment]
Any specific reason to add this? @gururajrkatti

**Comment by seth-priya** [comment]
@0xInfection this PR adds CI support for the IBM Power Little Endian (ppc64le) architecture. The idea is to ensure that the builds on this architecture are continuously tested along with the Intel builds (amd64) as this is part of the ubuntu distro on that architecture as well and detecting (and fixing) any issues or failures early would help to ensure that we are always up to date. Please let me know if that helps.

**Comment by gururajrkatti** [comment]
Hi @0xInfection, just wanted to check if you got a chance to look into this.

**Comment by gururajrkatti** [comment]
Thanks !

**Pull request merged**
