### PR TITLE
Pull request for dev

### PR DESCRIPTION
**Pull request by ChairsDaily**
#### Which category is this pull request?

- [ ] A new feature/enhancement.
- [x] Fix an issue/feature-request.
- [x] An improvement to existing modules.
- [ ] Other (Please mention below).

#### Where has this been tested?

- Python Version
    - [x] v3.x
    - [x] v2.x
- Operating System:
    - [x] Linux (Please specify distro)
    - [x] Windows
    - [ ] MacOS

#### Does this close any currently open issues? 
[Mention any issue which this PR closes]

#### Does this add any new dependency?
[Mention if this PR includes any new library]

#### Does this add any new command line switch/argument?
[Mention if the changes add any new arguments like `--arg`]

#### Any other comments you would like to make?
[Anything more you'd want the reviewer to know]

### CODE REVIEW

**Comment by ChairsDaily** [comment]
Ill be making several additions in the coming days, namely to the plugins. A lot of content and header matches are missing for some of the smaller firewalls.

**Comment by 0xInfection** [comment]
Hey @ChairsDaily, many thanks for pulling this up! Seems like an interesting addition. Please do ping us know when you've finished making changes for this PR, so we can review and merge this in!

> __Tip:__ If you're planning on making multiple changes, it would be better and cleaner making multiple PRs for each feature.

**Comment by ChairsDaily** [comment]
@0xInfection Good Morning from the Southern United States - I fixed some issues and name formatting. Everything is tested and working fine now. It is ready for merge. Ill be making PLENTY of future PRs addressing some of the out of date plugin modules as well as other testing methods that I have been researching. Have a great day!

**Comment by 0xInfection** [comment]
Thank you @ChairsDaily, much appreciated.

**Comment by ChairsDaily** [comment]
AHHHH I cant believe I missed that. The beauty of open source, we all have
each others backs to make the best software!!!

**Pull request merged**
